otodom_data_structure = {
    "url": None,
    "title": None,
    "address": None,
    "price": None,
    "offer_type": None,
    "area": None,
    "rooms": None,
    "heating": None,
    "floor": None,
    "rent": None,
    "building_condition": None,
    "market": None,
    "ownership_form": None,
    "available": None,
    "additional_info": None,
    "construction_year": None,
    "elevator": None,
    "windows": None,
    "energy_certificate": None,
    "equipment": None,
    "description": None,
}